# Woodpecker CI configuration for Plex Media Server
# Runtime download - single image supports all channels via VERSION env var

steps:
  - name: build
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.5.0/scripts/build.sh"
        chmod +x scripts/build.sh

        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/plex \
          --containerfile Containerfile \
          --base-version 15 \
          --tag latest \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: ["*.md", "docs/**", "LICENSE", ".gitignore"]
  - event: manual
