# Woodpecker CI configuration for Plex Media Server
# Builds 4 tags matching official pms-docker:
#   - latest/public: public channel
#   - beta/plexpass: plexpass channel

steps:
  - name: build-public
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.5.0/scripts/build.sh"
        chmod +x scripts/build.sh

        # Build public channel -> latest and public tags
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/plex \
          --containerfile Containerfile \
          --base-version 15 \
          --build-arg "PLEX_CHANNEL=public" \
          --tag latest \
          --alias public \
          --skip-wip \
          --login --push

  - name: build-plexpass
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.5.0/scripts/build.sh"
        chmod +x scripts/build.sh

        # Build plexpass channel -> plexpass and beta tags
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/plex \
          --containerfile Containerfile \
          --base-version 15 \
          --build-arg "PLEX_CHANNEL=plexpass" \
          --tag plexpass \
          --alias beta \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: ["*.md", "docs/**", "LICENSE", ".gitignore"]
  - event: manual
